name: Infisical Exports
description: Exports Infisical secrets to environment variables
author: Jeff Njoroge <jeff283>

inputs:
  infisical-client-id:
    description: "The Client ID of the Infisical application"
    required: true
  infisical-client-secret:
    description: "The Client Secret of the Infisical application"
    required: true
  infisical-project-id:
    description: "The ID of the Infisical project"
    required: true
  infisical-domain:
    description: The domain of the Infisical instance
    required: false
    default: "https://eu.infisical.com"
  infisical-env-slug:
    description: "The Slug of the Infisical environment"
    required: false
    default: "dev"

outputs:
  total-env-files:
    description: "Total number of .env files created"
  total-secrets:
    description: "Total number of secrets written across all .env files"
  env-file-paths:
    description: "JSON array of all .env file paths that were created"
  locations-file:
    description: "Path to the locations JSON file"
  duration-ms:
    description: "Time taken to complete the action in milliseconds"
  folder-append:
    description: "The folder append prefix used (or 'current directory' if empty)"

runs:
  using: node20
  main: dist/index.js
  post: dist/cleanup.js
